### ISSUE TITLE
List everything in the design that needs to be affected by the primary/secondary colors, and how

### ISSUE THREAD

**Issue by akariv** [whiletrue-industries/Chronomaps#22]

**Comment by mushon** [comment]
It's basically everywhere the primary and the secondary appear.
If you want I can try to mark some additional spots where they are used less conventionally (box-shadows, gradients, SVGs etc...), but otherwise, it is everywhere, so in most cases using a variable should do the trick.
As for Mapbox, I do realize the style is handled differently, I do not expect the variable color to affect the style, but I think we can keep the markers outside of the canvas element so they should be controllable that way.

**Comment by akariv** [comment]
Yes, I was referring to all the 'others' which need to be somehow affected from the primary/secondary color settings. It's not trivial for me to guess how a certain setting (e.g. box shadow) derives from the primary/secondary colors...

**Comment by akariv** [comment]
btw, map markers are already based on the color settings, external to the map.

**Comment by mushon** [comment]
I consolidated the colors in Figma to:
- Primary
- Secondary
- Primary-0.25 trans
- Primary-0.07 tint
- Secondary-0.35 trans

Figma doesn't allow me to use color styles in effects (like drop shadows) but those also use either primary or secondary

**Comment by akariv** [comment]
What is "Primary-0.07 tint" ?

**Comment by mushon** [comment]
It’s transparency on a white background. If you use LESS CSS you can refer to it here: https://lesscss.org/functions/#color-operations-tint

**Comment by akariv** [comment]
Thanks! less is not relevant for us as it does the calculations during
build time and we read the color during runtime.

**Comment by mushon** [comment]
https://caniuse.com/mdn-css_types_color_color-mix

**Comment by akariv** [comment]
So it would be  color-mix(in srgb, <color> 7%, white)? i.e. mostly white?

**Comment by mushon** [comment]
Yes, I think so

**Comment by mushon** [comment]
The contribution flow still has some hard coded colors:
![Image](https://github.com/whiletrue-industries/Chronomaps/assets/27123/147e4cf1-377f-4285-8c3d-18ac906a5064)

![Image](https://github.com/whiletrue-industries/Chronomaps/assets/27123/855f2b85-503d-4e72-9fd8-4d4b7b7b970f)

**Comment by akariv** [comment]
Can you check the contribution flow now?
